apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-api-deployment
spec:
  selector:
    matchLabels:
      app: star-wars-api
  replicas: 2
  template:
    metadata:
      labels:
        app: star-wars-api
    spec:
      containers:
      - name: star-wars-api
        image: kennethgaz/star-wars-api:1.0.0
        ports:
        - containerPort: 8080
